function PSI = getPsi(x)
%get matrix psi mapping between derivative of unit dual qaut x and pure quat representing linear velocity
% vec(v) = PSI*vec(dot_x)
x = x.q; 
A = [x(5)  x(6)  x(7)  x(8); ...
     x(6) -x(5)  x(8) -x(7); ...
     x(7) -x(8) -x(5)  x(6); ...
     x(8)  x(7) -x(6) -x(5)];
B = [ x(1)   x(2)  x(3) x(4); ...
     -x(2)  x(1) -x(4)  x(3); ...
     -x(3)  x(4)  x(1) -x(2); ...
     -x(4) -x(3)  x(2)  x(1)];
PSI = 2*[A,B];
end

